(function(){
  async function getMe(){ try{ const r=await fetch('/api/auth/me',{credentials:'include'}); const d=await r.json(); return d.user||null; }catch(_){ return null; } }
  function extractLectureId(el){ const a=el.querySelector('a[href^="/api/lectures/"]'); if(!a) return null; const m=a.getAttribute('href').match(/\/api\/lectures\/(\d+)/); return m?Number(m[1]):null; }
  function ensureModal(){ let m=document.getElementById('commentsModal'); if(m) return m; m=document.createElement('div'); m.id='commentsModal'; m.style.position='fixed'; m.style.inset='0'; m.style.background='rgba(0,0,0,.6)'; m.style.display='none'; m.style.zIndex='9999'; const box=document.createElement('div'); box.style.maxWidth='700px'; box.style.margin='5vh auto'; box.style.background='var(--card)'; box.style.padding='14px'; box.style.borderRadius='10px'; box.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px"><h3 style="margin:0">إدارة التعليقات</h3><button class="btn" id="cClose">إغلاق</button></div><div id="cBody" class="grid"></div>';
    m.appendChild(box); document.body.appendChild(m); box.querySelector('#cClose').onclick=()=>{ m.style.display='none'; }; return m; }
  async function openCommentsAdmin(lectureId){ const modal=ensureModal(); const body=modal.querySelector('#cBody'); body.innerHTML='<div class="meta">...جار التحميل</div>'; modal.style.display='block'; try{ const r=await fetch(`/api/lectures/${lectureId}/comments`,{credentials:'include'}); const d=await r.json(); body.innerHTML=''; (d.items||[]).forEach(c=>{ const item=document.createElement('div'); item.className='lecture'; item.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><div><strong>${c.username}</strong><div class="meta">${new Date(c.created_at).toLocaleString()}${c.edited_at?` • معدّل ${new Date(c.edited_at).toLocaleString()}`:''}</div><div style="margin-top:6px">${(c.text||'').replace(/</g,'&lt;')}</div></div><div style="display:flex;gap:6px"><button class="btn" data-edit>تعديل</button><button class="btn btn-danger" data-del>حذف</button></div></div>`; item.querySelector('[data-edit]').onclick=async()=>{ const next=prompt('النص الجديد:', c.text||''); if(next===null) return; const r=await fetch(`/api/lectures/${lectureId}/comments/${c.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({text:next})}); if(r.ok){ openCommentsAdmin(lectureId); } else { window.toast&&toast('تعذر التعديل'); } }; item.querySelector('[data-del]').onclick=async()=>{ if(!confirm('حذف التعليق؟')) return; const r=await fetch(`/api/lectures/${lectureId}/comments/${c.id}`,{method:'DELETE',credentials:'include'}); if(r.ok){ openCommentsAdmin(lectureId); } else { window.toast&&toast('تعذر الحذف'); } }; body.appendChild(item); }); if(!body.children.length){ body.innerHTML='<div class="meta">لا توجد تعليقات</div>'; } }catch(_){ body.innerHTML='<div class="meta">تعذّر التحميل</div>'; } }
  async function enhance(el, me){ if(!(me && (me.role==='teacher'||me.role==='owner'))) return; if(!document.getElementById('teacherLectures')) return; if(el.querySelector('[data-comments-admin]')) return; const id=extractLectureId(el); if(!id) return; const bar=el.querySelector('[data-privacy-ui]')?.parentElement || el; const btn=document.createElement('button'); btn.className='btn'; btn.dataset.commentsAdmin='1'; btn.textContent='التعليقات'; btn.onclick=()=>openCommentsAdmin(id); const container=el.querySelector('[data-privacy-ui]')||el; if(container.firstChild && container.firstChild.firstChild){ container.firstChild.appendChild(btn); } else { const wrap=document.createElement('div'); wrap.style.marginTop='6px'; wrap.appendChild(btn); el.appendChild(wrap); } }
  async function attachCommentsAdmin(){ const me=await getMe(); const apply=()=>{ document.querySelectorAll('.lecture').forEach(el=>enhance(el, me)); }; apply(); const obs=new MutationObserver(()=>apply()); const root=document.getElementById('teacherLectures'); if(root) obs.observe(root,{childList:true,subtree:true}); }
  window.attachCommentsAdmin=attachCommentsAdmin;
})();
